### ISSUE TITLE
`UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 51` during curation

### ISSUE THREAD

**Issue by j-berg** [Metaboverse/Metaboverse#59]
```
Operating System information:
5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Metaboverse/0.3.0b Chrome/80.0.3987.165 Electron/8.3.4 Safari/537.36



Metaboverse-CLI version: 0.3.0-beta
======================
User commands summary:
======================
cmd: curate
output: /Users/***/Desktop/
species_id: MMU
organism_curation: None
model_file: /Users/***/Desktop/MMU_metaboverse_db.pickle
output_file: /Users/***/Desktop/Untitled.json
transcriptomics: /Users/***/Desktop/TranscriptomicDiffExpInputFileForMetaboverse_EnsemblIDs.txt
proteomics: None
metabolomics: /Users/***/Desktop/MetabolomicInputForMetaboverse.txt
collapse_with_modifiers: False
broadcast_genes: True
experiment_type: None
experiment_name: None
labels: 0
blocklist: H+,H2O,CO2,e-,Mn2+,K+,Na+,Mg2+,O2,H2O2
session_data: /Users/***/Library/Application Support/Metaboverse/session_data.json
progress_log: /Users/***/Library/Application Support/Metaboverse/progress_log.json
path: /private/var/folders/***/***/***
=====================
End commands summary
=====================

Curating network model...
Curating Reactome network database. Please be patient, this will take several minutes...
Loading reactions...
No notes available for CHEK1 phosphorylates TP53
No notes available for SPRED dimer binds NF1
No notes available for PP2A binds CTLA4 homodimer
No notes available for 


########
STDERR:
########
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 29  127M   29 37.7M    0     0  34.9M      0  0:00:03  0:00:01  0:00:02 34.9M
 69  127M   69 88.6M    0     0  42.6M      0  0:00:02  0:00:02 --:--:-- 42.6M
100  127M  100  127M    0     0  45.6M      0  0:00:02  0:00:02 --:--:-- 45.6M
Traceback (most recent call last):
  File "metaboverse_cli/curate/load_reactions_db.py", line 154, in get_metadata
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "metaboverse_cli/__main__.py", line 165, in <module>
  File "metaboverse_cli/__main__.py", line 140, in main
  File "metaboverse_cli/curate/__main__.py", line 362, in __main__
  File "metaboverse_cli/curate/load_reactions_db.py", line 550, in __main__
  File "metaboverse_cli/curate/load_reactions_db.py", line 458, in process_components
  File "metaboverse_cli/curate/load_reactions_db.py", line 162, in get_metadata
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 51: ordinal not in range(128)
[36017] Failed to execute script __main__

```

**Comment by j-berg** [comment]
I try to run the same function for mouse, and all seems to work fine here:
```
No notes available for G alpha (i):RGS dissociates to inactive G alpha (i)–i1/i2/i3
No notes available for SPRED dimer binds NF1
No notes available for PP2A binds CTLA4 homodimer
No notes available for CHEK1 phosphorylates TP53
```

Strangely, the reactions with missing notes are different. It looks like the issue is coming from a name that is blank or with a bad character based on the last alert is the user's example where no reaction name is printed.

**Comment by j-berg** [comment]
Addressed in: https://github.com/Metaboverse/metaboverse-cli/commit/287e1a21b64d18fb043c38770ad5564cd0e3e136
Hopefully, this workaround will lead to better flexibility for any edge cases where a weird character might break the process.
- Force reaction attributes, `id`, `name`, and `compartment` to a string

**Comment by j-berg** [comment]
v0.3.1b for macOS is still running into this issue. If you curate mouse on Windows, it works fine, but if you curate mouse on macOS, this error occurs. macOS is able to handle other organisms, like yeast, just fine. Will continue looking for solutions.

**Comment by j-berg** [comment]
This does not occur on Linux

**Comment by j-berg** [comment]
Closed by https://github.com/Metaboverse/metaboverse-cli/commit/eb01b02ab9b45e28bad324e21d1f02bbefc32d8d, updated in `v0.3.2b`
